// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type StockDaily struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	TradeDate time.Time `json:"trade_date"`
	Open      string    `json:"open"`
	High      string    `json:"high"`
	Low       string    `json:"low"`
	Close     string    `json:"close"`
	Vol       int64     `json:"vol"`
	Amount    string    `json:"amount"`
	CreateAt  time.Time `json:"create_at"`
}
