// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateStockDaily(ctx context.Context, arg CreateStockDailyParams) error
}

var _ Querier = (*Queries)(nil)
