// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CreateStockBrief(ctx context.Context, arg CreateStockBriefParams) error
	CreateStockDaily(ctx context.Context, arg CreateStockDailyParams) error
	GetStockBrief(ctx context.Context, code string) (StockBrief, error)
	UpdateStockBrief(ctx context.Context, arg UpdateStockBriefParams) error
}

var _ Querier = (*Queries)(nil)
