// Code generated by sqlc. DO NOT EDIT.
// source: stock.sql

package db

import (
	"context"
	"time"
)

const createStockDaily = `-- name: CreateStockDaily :exec
INSERT INTO stock_daily ( code, trade_date, open, high,low,close,vol,amount )
VALUES
    ( $1, $2, $3, $4,$5,$6,$7,$8 )
`

type CreateStockDailyParams struct {
	Code      string    `json:"code"`
	TradeDate time.Time `json:"trade_date"`
	Open      string    `json:"open"`
	High      string    `json:"high"`
	Low       string    `json:"low"`
	Close     string    `json:"close"`
	Vol       int64     `json:"vol"`
	Amount    string    `json:"amount"`
}

func (q *Queries) CreateStockDaily(ctx context.Context, arg CreateStockDailyParams) error {
	_, err := q.db.ExecContext(ctx, createStockDaily,
		arg.Code,
		arg.TradeDate,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Vol,
		arg.Amount,
	)
	return err
}
